# server port config
server:
  port: 8887
# custom error page config
  error:    include-exception: true
    include-stacktrace: ALWAYS
    whitelabel:      enabled: false
# oracle driver config
spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@localhost:1521:xe
    username: EGV
    password: EGV
  devtools: 
    livereload: 
        enabled: true 
# jpa config  jpa:    generate-ddl: false
    show-sql: true
    database: oracle    database-platform: org.hibernate.dialect.Oracle10gDialect# file upload config  servlet:    multipart:      max-file-size: 10MB      max-request-size: 20MBlogging:  level:
      root: warn
#    '[org.hibernate]': info
